### ISSUE TITLE
Built with rust1.83.0, there may be some warnings that I hope can be fixed.

### ISSUE THREAD

**Issue by mzdk100** [countercept/mongo-rs#11]
warning: non-local `impl` definition, `impl` blocks should be written at the same level as their item
 --> src\space.rs:6:57
  |
6 | #[derive(Clone, Debug, Default, Serialize, Deserialize, Bson, Mongo)]
  |                                                         -^^^
  |                                                         |
  |                                                         `Bson` is not local
  |                                                         `TryFrom` is not local
  |                                                         move the `impl` block outside of this constant `_IMPL_BSON_FOR__SpaceInfo`
7 | #[mongo(collection = "spaces", oid, field, filter, update)]
8 | pub struct SpaceInfo {
  |            --------- `SpaceInfo` is not local
  |
  = note: the derive macro `Bson` defines the non-local `impl`, and may need to be changed
  = note: the derive macro `Bson` may come from an old version of the `mongod_derive` crate, try updating your dependency with `cargo update -p mongod_derive`
  = note: an `impl` is never scoped, even when it is nested inside an item, as it may impact type checking outside of that item, which can be the case if neither the trait or the self type are at the same nesting level as the `impl`
  = note: items in an anonymous const item (`const _: () = { ... }`) are treated as in the same scope as the anonymous const's declaration for the purpose of this lint
  = note: `#[warn(non_local_definitions)]` on by default
  = note: this warning originates in the derive macro `Bson` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by alexkornitzer** [comment]
Thanks for raising this, I have a fix pending, I just need to fix my access to the repo after which I can then push the build up.
